<?php
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_detalhes-curso',
		'title' => 'Detalhes - CURSO',
		'fields' => array (
			array (
				'key' => 'field_578e3225ed054',
				'label' => 'Pagamento via Pagseguro?',
				'name' => 'pagamento_via_pagseguro',
				'type' => 'true_false',
				'instructions' => 'Marque essa opção para exibição do botão de compra via Pagseguro',
				'message' => '',
				'default_value' => 1,
			),
			array (
				'key' => 'field_5790c2471a858',
				'label' => 'Primeiro Lote - Data',
				'name' => 'primeiro_lote_data',
				'type' => 'date_picker',
				'date_format' => 'yy-mm-dd',
				'display_format' => 'dd/mm/yy',
				'first_day' => 1,
			),
			array (
				'key' => 'field_5790c30f68e82',
				'label' => 'Primeiro Lote - Valor',
				'name' => 'primeiro_lote_valor',
				'type' => 'number',
				'instructions' => 'Insira o valor do PRIMEIRO LOTE a ser disponibilizado',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_5790c2ca68e80',
				'label' => 'Segundo Lote - Data',
				'name' => 'segundo_lote_data',
				'type' => 'date_picker',
				'date_format' => 'yy-mm-dd',
				'display_format' => 'dd/mm/yy',
				'first_day' => 1,
			),
			array (
				'key' => 'field_5790c2bb68e7f',
				'label' => 'Segundo Lote - Valor',
				'name' => 'segundo_lote_valor',
				'type' => 'number',
				'instructions' => 'Insira o valor do SEGUNDO LOTE a ser disponibilizado',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_5790c2dd68e81',
				'label' => 'Terceiro Lote - Data',
				'name' => 'terceiro_lote_data',
				'type' => 'date_picker',
				'date_format' => 'yy-mm-dd',
				'display_format' => 'dd/mm/yy',
				'first_day' => 1,
			),
			array (
				'key' => 'field_5790c34168e83',
				'label' => 'Terceiro Lote - Valor',
				'name' => 'terceiro_lote_valor',
				'type' => 'number',
				'instructions' => 'Insira o valor do TERCEIRO LOTE a ser disponibilizado',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_578e30c1dab8e',
				'label' => 'Professores',
				'name' => 'professores',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'professor',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 0,
				'multiple' => 1,
			),
			array (
				'key' => 'field_578e318ded04d',
				'label' => 'Horários',
				'name' => 'horarios',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_578e319ded04e',
				'label' => 'Objetivos',
				'name' => 'objetivos',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_578e31aaed04f',
				'label' => 'Público Alvo',
				'name' => 'publico_alvo',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_578e31c3ed050',
				'label' => 'Conteúdo Programático',
				'name' => 'conteudo_programatico',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
			array (
				'key' => 'field_578e321aed053',
				'label' => 'Carga Horária',
				'name' => 'carga_horaria',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_578e896fee5cf',
				'label' => 'Período',
				'name' => 'periodo',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_578e89bdee5d0',
				'label' => 'Local',
				'name' => 'local',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_578e8a04ee5d1',
				'label' => 'Coordenação',
				'name' => 'coordenacao',
				'type' => 'text',
				'default_value' => 'Paulo Almada',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_578e8a24c2677',
				'label' => 'Contatos',
				'name' => 'contatos',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_578e8a2ec2678',
				'label' => 'E-mail',
				'name' => 'email',
				'type' => 'email',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'curso',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_cnae',
		'title' => 'CNAE',
		'fields' => array (
			array (
				'key' => 'field_5912121222d6b',
				'label' => 'Número',
				'name' => 'numero',
				'type' => 'number',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_5912123922d6c',
				'label' => 'Base legal',
				'name' => 'base_legal',
				'type' => 'textarea',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5912125822d6d',
				'label' => 'Link',
				'name' => 'link',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'http://',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'cnae',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_cests',
		'title' => 'CESTs',
		'fields' => array (
			array (
				'key' => 'field_592d89e319779',
				'label' => 'ITEM',
				'name' => 'item',
				'type' => 'text',
				'instructions' => 'Edite o número do Item:',
				'required' => 1,
				'default_value' => '',
				'placeholder' => 'Edite o número do Item:',
				'prepend' => 'item_',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_592d8a1f1977a',
				'label' => 'CEST',
				'name' => 'cest',
				'type' => 'text',
				'instructions' => 'Edite o número dessa CEST:',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_592d8a401977b',
				'label' => 'NCM',
				'name' => 'ncm_sh',
				'type' => 'repeater',
				'instructions' => 'Edite a NCM dessa CEST',
				'required' => 1,
				'sub_fields' => array (
					array (
						'key' => 'field_592dabd69e0d2',
						'label' => 'NCM',
						'name' => 'ncm_item_sh',
						'type' => 'text',
						'required' => 1,
						'column_width' => 50,
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add NCM',
			),
			array (
				'key' => 'field_592d8a541977c',
				'label' => 'Descricão CEST',
				'name' => 'descricao_cest',
				'type' => 'textarea',
				'instructions' => 'Edite a descrição desta CEST: ',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 8,
				'formatting' => 'br',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'cest',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'the_content',
				2 => 'excerpt',
				3 => 'custom_fields',
				4 => 'discussion',
				5 => 'comments',
				6 => 'revisions',
				7 => 'slug',
				8 => 'author',
				9 => 'format',
				10 => 'featured_image',
				// 11 => 'categories',
				12 => 'tags',
				13 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
}
